### PR TITLE
Feed new

### PR DESCRIPTION
**Pull request by howdoicomputer**

### CODE REVIEW

**Comment by kyleady** [comment]
Do Not Merge - A new instance of FeedList needs to be initialized permanently to maintain a list of the feeds that the user has submitted.

**Comment by howdoicomputer** [comment]
Okay, so I did a few things.

What we really wanted was, instead of an array to represent articles attached to a feed, I created a new model to track articles. Note, I changed items to articles. Then I created an [association](http://guides.rubyonrails.org/association_basics.html) between feeds and articles so that a feed `has_many` articles and an article `belongs_to` a single feed.

So the reason why your `Feed` objects weren't saving was because you were adding `attr_accessor` to your model code. Now, this is great for reading and writing attributes to `class`es but it's not so great in this context. Why? Because `ActiveModel` handles this magic for you. It assumes that you're going to want to read and write attributes to an object so it automatically generates that capability - by providing `attr_accessor` you are essentially overwriting `ActiveModel's` functionality.

I also noticed that `Article < ActiveRecord::Base` changed to `Article < ApplicationRecord` for Rails 5 so I modified the relevant code in our models.

In order to enhance your work and add in mine, I used the Rails generator to generate migrations. Migrations are the codified transactions used to change our schema. A schema is the written down 'structure' our data is taking in our database - eg. how columns, rows, foreign keys, etc are laid out. You can take a look at `db/schema.rb` now to get an idea of what our database looks like.

Here are the generator commands I used:
- Generate a new model called article and tell it that it belongs to a feed.
  - `rails g model article title:string feed:belongs_to`
- Give it the attributes we want.
  - `rails g migration AddColumsToArticles description:string link:string author:string pub_date:string guid:string`
- Get rid of items from the feed model.
  - `rails g migration RemoveItemsFromFeed items:text`
- Add articles to feed.
  - `rails g migration AddArticlesToFeed feed:has_many`

I probably could have been more efficient with my commands but that got what I needed. I then dropped my tables from my database (deleted a bunch of stuff) and then ran my migrations. These actions are bundled up in the single command `rails db:reset`.

I then changed our `/feeds` `show` template so that the articles that belong to a single feed are iterated over and their titles are printed out under a feed. We can work on cleaning up this view code in some other issue but it seemed to work after I added [smbc's rss feed](http://www.smbc-comics.com/rss.php).

**Comment by howdoicomputer** [comment]
[Here is an example migration generated by the generation command](https://github.com/kyleady/uss_rss_reader/blob/8f95b92edf6d87fce50a6e3100ddc08d5d5751ca/db/migrate/20160802220608_add_colums_to_articles.rb) where it adds new columns to the articles table.

I'd also like to take a moment to talk about the `map` function for Ruby. It iterates over a collection, modifies each element of that collection, and then returns the modified elements in a _new_ collection.

I added an example to the `scratch` directory for you to [look at](https://github.com/kyleady/uss_rss_reader/blob/8f95b92edf6d87fce50a6e3100ddc08d5d5751ca/scratch/rss_feed_smbc_map.rb). It is a handy function because it can lead to some very concise and readable code.

We'll also need to add ~~~~~*****_TESTS**_****~~~~~ eventually. I'll write some for us to begin with in a different pull request.

**Comment by howdoicomputer** [comment]
@kyleady As a small exercise, see if you can get the view for `/feeds/:id` to print links to the articles instead of the article titles.

**Pull request merged**
